### ISSUE TITLE
Converting sim8f and simd8i

### ISSUE THREAD

**Issue by pythonanonuser** [fastfastball/arm_neon_for_dlib_simd#2]
I've tried your version of dlib for NEON instructions and have definitely noticed a speedup. However the face detection is still pretty laggy for me even at a 640x480 resolution. I suspect it is because of the use of the `simd8f.h` and `simd8i.h` files in `fhog.h`. I was wondering if you had any plans to convert those. I am willing to give it a try, but am not too familiar with NEON and would need to know how to start. Thanks!

**Comment by fastfastball** [comment]
Hi, I suggest you to try https://github.com/fastfastball/dlib_for_arm . 3 enhancements have been made in it. In Android 5.0@Cortex-A53 1.4Ghz 4 cores platform, I think, with these enhancement, it only takes < 70ms to do face detection in a 640X480 picture.  You said that you use cortex-a57. I think it may take you only 35ms.

If the performance is still not good enough, there are still several methods you can try
1) if in your application you only need to detect "big faces", plz reduce 640x480 to smaller one(for ex: 320X240)
2) pay attention to thermal issues. Some BSP may slow down or even turn off some CPU cores if temp is high enough.
3) check http://stackoverflow.com/questions/38435653/detecting-face-landmarks-points-in-android

**Comment by pythonanonuser** [comment]
Thank you, I will these a shot.
